#########################
#
# Utility script to run the test using the provided test type
#
# Parameters:
#   - type: test type, either tcp, rpc
#   - ntasks: number of tasks generated by the Source node in the application,
#             note that the LNode will generate 2 tasks per item received from the Source.
#   - protocol: only needed when running the 'rpc' test, specifies the Margo protocol
#   - port: base port number to be used for the communications, all the groups
#           will listen on the base port number + their ID
#
#
# Author:
#   Federico Finocchio
#
#########################

type=${1:-tcp}
ntasks=${2:-10000}
protocol=${3:-""}
port=${4:-""}

ssh -tt compute4 "./${type}_test.out 3 $ntasks $protocol $port 2>&1 > ./log3.${type}.txt"
ssh -tt compute3 "./${type}_test.out 2 $ntasks $protocol $port > /dev/null"
ssh -tt compute2 "./${type}_test.out 1 $ntasks $protocol $port > /dev/null"
ssh -tt compute1 "./${type}_test.out 0 $ntasks $protocol $port > /dev/null"
