#########################
#
# Utility script to run the performance test using the TCP protocol and the
# specified test type.
#
# Parameters:
#   - ttype: test type, either TCPSP, TCPMP, TCPRPC
#   - ntasks: number of tasks generated by the Source node in the application,
#             note that the LNode will generate 4 tasks per item received from the Source.
#   - msgsize: size in bytes to use for each of the tasks generated by the LNodes
#   - lmswait: ms of wait time for the LNode
#   - rmswait: ms of wait time for the RNode
#
#
# Author:
#   Federico Finocchio
#
#########################

type=${1:-TCPSP}
ntasks=${2:-1000}
msgsize=${3:-500}
lmswait=${4:-0}
rmswait=${5:-0}

ssh -tt compute4 "./${type}_performance.out 3 $ntasks $msgsize $lmswait $rmswait >> ./tcpres/${type}.txt" &
ssh -tt compute3 "./${type}_performance.out 2 $ntasks $msgsize $lmswait $rmswait > /dev/null" &
ssh -tt compute2 "./${type}_performance.out 1 $ntasks $msgsize $lmswait $rmswait > /dev/null" &
ssh -tt compute1 "./${type}_performance.out 0 $ntasks $msgsize $lmswait $rmswait > /dev/null" &