#########################
#
# Utility script to run the performance test using the MPI protocol and the
# specified test type.
#
# Parameters:
#   - ttype: test type, either MPISP, MPIMP, MPIMIX
#   - ntasks: number of tasks generated by the Source node in the application,
#             note that the LNode will generate 4 tasks per item received from the Source.
#   - msgsize: size in bytes to use for each of the tasks generated by the LNodes
#   - lmswait: ms of wait time for the LNode
#   - rmswait: ms of wait time for the RNode
#
#
# Author:
#   Federico Finocchio
#
#########################

ttype=${1:-MPISP}
ntasks=${2:-1000}
msgsize=${3:-1024}
lmswait=${4:-0}
rmswait=${5:-0}

mpirun -n 4 --hostfile myhosts --map-by node sh -c "./${ttype}_performance.out 0 $ntasks $msgsize $lmswait $rmswait >> /home/f.finocchio/multi-protocol-DFF/tests/mpires/${ttype}.\$OMPI_COMM_WORLD_RANK.txt"